# Generated by scripts/generate_release_metadata.py from RELEASE_MANIFEST.json.
__version__ = '4.2.0'
__release_id__ = '41141a3e-9c36-4a30-a149-1d9321c6bcdb'
__artifact_filename__ = 'PARMESAN_v4_2_0.zip'
