# Generated by scripts/generate_release_metadata.py from RELEASE_MANIFEST.json.
__version__ = '2.7.1'
__release_id__ = '94414256-87db-4b36-9571-d09028606853'
__artifact_filename__ = 'PARMESAN_v2_7_1.zip'
