# Generated by scripts/generate_release_metadata.py from RELEASE_MANIFEST.json.
__version__ = '4.0.1'
__release_id__ = 'c1437c4c-ec7a-467f-a02d-5d3ffdd979e0'
__artifact_filename__ = 'PARMESAN_v4_0_1.zip'
