#!/usr/bin/env python3
"""Generate every release-facing metadata file from RELEASE_MANIFEST.json.

Do not edit RELEASE.json, RELEASE.md, src/parmesan/version.py, or the project
version by hand.  This script is the only supported release-metadata writer.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "RELEASE_MANIFEST.json"


def load_manifest() -> dict[str, object]:
    manifest = json.loads(SOURCE.read_text(encoding="utf-8"))
    version = str(manifest["version"])
    expected_filename = f"PARMESAN_v{version.replace('.', '_')}.zip"
    expected_root = f"PARMESAN_v{version.replace('.', '_')}"
    if manifest.get("artifact_filename") not in (None, expected_filename):
        raise ValueError("RELEASE_MANIFEST.json artifact_filename conflicts with version")
    if manifest["root_directory"] != expected_root:
        raise ValueError("RELEASE_MANIFEST.json root_directory conflicts with version")
    manifest["artifact_filename"] = expected_filename
    return manifest


def release_markdown(release: dict[str, object]) -> str:
    return f"""# Parmesan release and delivery convention

This artifact is **Parmesan {release['version']}**.

- Human filename: `{release['artifact_filename']}`
- Root directory after unpacking: `{release['root_directory']}/`
- Immutable release ID: `{release['release_id']}`
- Artifact type: conversational-LLM software; no corpus is bundled

## Versioning

Parmesan uses `MAJOR.MINOR.PATCH`:

- **MAJOR** changes when the PGX meaning, database compatibility, or core tool contract changes incompatibly.
- **MINOR** changes for backward-compatible capabilities or substantial workflow additions.
- **PATCH** changes for backward-compatible fixes, clearer operating instructions, or release hardening.

A delivered version is immutable. If any byte changes after delivery, increment the version and generate a new release UUID. Do not silently rebuild the same version.

## Naming and identity

The archive name stays readable: `PARMESAN_vMAJOR_MINOR_PATCH.zip`. The UUID does **not** belong in the filename. It lives in `RELEASE.json` and in the doctor result so an LLM can distinguish exact releases without making the handoff ugly.

The final ZIP SHA-256 is the identity of the delivered bytes. It is reported alongside the single download link at handoff. Internal files are covered by `PACKAGE_MANIFEST.json` and `SHA256SUMS.txt`.

## Single source of truth

`RELEASE_MANIFEST.json` is the only authored release-identity record. `RELEASE.json`, this file, the runtime version module, and package metadata are generated or checked from it. Run `python scripts/generate_release_metadata.py` after changing the source manifest; never edit generated release identity by hand.

## Standard handoff

A normal Parmesan release is delivered as exactly one primary ZIP. The final response should state the version, release ID, ZIP SHA-256, and validation result, then provide one link whose text is the exact filename. Additional report links are included only when specifically useful or requested.

## Traversal documentation

This release preserves the supplied `PGX_Traversal_4C_Guide` documents verbatim under `docs/PGX_Traversal_4C_Guide/`. They are part of the required operating path and their source hashes are enforced by release validation.
"""


def main() -> None:
    release = load_manifest()
    (ROOT / "RELEASE.json").write_text(json.dumps(release, indent=2) + "\n", encoding="utf-8")
    (ROOT / "RELEASE.md").write_text(release_markdown(release), encoding="utf-8")
    (ROOT / "src" / "parmesan" / "version.py").write_text(
        "# Generated by scripts/generate_release_metadata.py from RELEASE_MANIFEST.json.\n"
        f"__version__ = {release['version']!r}\n"
        f"__release_id__ = {release['release_id']!r}\n"
        f"__artifact_filename__ = {release['artifact_filename']!r}\n",
        encoding="utf-8",
    )
    print(json.dumps({key: release[key] for key in ("version", "release_id", "artifact_filename", "root_directory")}, indent=2))


if __name__ == "__main__":
    main()
